/**
 * Contains all the ui tests.
 */
define([
    'ui/compileIntegrationSpec',
    'ui/angularUrlIntegrationSpec',
    'ui/buttonSpec',
    'ui/checkBoxSpec',
    'ui/collapsibleSpec',
    'ui/eventSpec',
    'ui/inputButtonSpec',
    'ui/inputSliderSpec',
    'ui/listViewSpec',
    'ui/ngmClickSpec',
    'ui/radioSpec',
    'ui/selectmenuSpec',
    'ui/selectSliderSpec',
    'ui/textInputSpec',
    'ui/waitDialogServiceSpec'
]);