/**
 * Contains all the unit-tests.
 */
define([
    'jqm-angular',
    'unit/eventSpec',
    'unit/navigateSpec',
    'unit/arrayPagingSpec',
    'unit/iffSpec',
    'unit/ifSpec',
    'unit/sharedControllerSpec',
    'unit/repeatSpec',
    'unit/buttonSpec',
    'unit/checkBoxSpec',
    'unit/collapsibleSpec',
    'unit/inputButtonSpec',
    'unit/inputSliderSpec',
    'unit/radioSpec',
    'unit/selectSliderSpec',
    'unit/textInputSpec',
    'unit/listViewSpec',
    'unit/switchSpec'
]);
