// Wrapper module as facade for the internal modules.
define([
    'angular',
    'jquery',
    'jqmng/globalScope',
    'jqmng/navigate',
    'jqmng/waitDialog',
    'jqmng/event',
    'jqmng/fadein',
    'jqmng/if',
    'jqmng/paging',
    'jqmng/sharedController',
    'jqmng/widgets/pageCompile',
    'jqmng/widgets/angularRepeat',
    'jqmng/widgets/angularSwitch',
    'jqmng/widgets/angularInput',
    'jqmng/widgets/angularSelect',
    'jqmng/widgets/disabledHandling',
    'jqmng/widgets/jqmButton',
    'jqmng/widgets/jqmListView',
    'jqmng/widgets/jqmSelectMenu',
    'jqmng/widgets/jqmSlider',
    'jqmng/jqmngStyle'
]);